### ISSUE TITLE
Syntax highlighting breaks when editing a posted comment

### ISSUE THREAD

**Issue by leNEKO** [exercism/bugs#11]
Here an sample
![image](https://user-images.githubusercontent.com/55792/45149464-e5fe6f00-b1c9-11e8-90bf-cf84daeb0c04.png)

When editing and save it loose colors
![image](https://user-images.githubusercontent.com/55792/45149517-08908800-b1ca-11e8-966e-7aff568c8f6a.png)

But it is fixed back when adding another comment
![image](https://user-images.githubusercontent.com/55792/45149582-32e24580-b1ca-11e8-9041-f6a934309632.png)

**Comment by kntsoriano** [comment]
@iHiD Seems to be fixed. I have no permissions to close this issue.

**Comment by iHiD** [comment]
@kntsoriano Great thanks. You now have permissions.
