### ISSUE TITLE
/team/mentors pagination issue

### ISSUE THREAD

**Issue by rpottsoh** [exercism/bugs#12]
@Falci commented on [Sat Dec 15 2018](https://github.com/exercism/website-copy/issues/664)

The [three](https://exercism.io/team/mentors?page=9) [last](https://exercism.io/team/mentors?page=10) [pages](https://exercism.io/team/mentors?page=11) of mentors seems to be wrong. The same mentor appear in all of them.

---

@rpottsoh commented on [Sun Dec 16 2018](https://github.com/exercism/website-copy/issues/664#issuecomment-447693408)

Pages [10](https://exercism.io/team/mentors?page=10) and [11](https://exercism.io/team/mentors?page=11) are not needed.

cc: @iHiD 

---

@rpottsoh commented on [Sun Dec 16 2018](https://github.com/exercism/website-copy/issues/664#issuecomment-447693497)

I am going to move this to exercism/exercism.

**Comment by rpottsoh** [comment]
> see if this is still an issue

I am not able to recreate it anymore.  Side note, there are 14 pages of mentors when before there was only 9.  👍

**Comment by iHiD** [comment]
Thanks :)
