### ISSUE TITLE
Deleting Account does not work

### ISSUE THREAD

**Issue by max-leuthaeuser** [exercism/bugs#16]
When trying to delete my account via ```https://exercism.io/my/settings/confirm_delete_account``` I am just getting:
```
Oh dear, something's not working here. Sorry about that.
Continue by heading back to the homepage.
```

**Comment by iHiD** [comment]
@kntsoriano Please can you look at this one.

**Comment by iHiD** [comment]
@max-leuthaeuser This should work now. Sorry for the inconvenience.

**Comment by max-leuthaeuser** [comment]
Worked perfectly. Thanks!

**Comment by iHiD** [comment]
Great. Could I ask why you chose to delete your account? :)
