### ISSUE TITLE
Page hanging for a particular solution of mine

### ISSUE THREAD

**Issue by glennj** [exercism/bugs#17]
It's my solution to Gigasecond in Common Lisp: https://exercism.io/my/solutions/54e02b243f00441487703c858765b524

This page hangs, pegs my CPU at 100%, and eventually the tab crashes. I'll attach a screenshot with devtools.

It hangs in Brave browser and Chrome but not Safari. In a Windows VM, Edge hangs too.

<img width="1752" alt="Screen Shot 2019-08-04 at 6 11 45 PM" src="https://user-images.githubusercontent.com/122470/62430099-99772880-b6e5-11e9-9730-697ce13f3368.png">

**Comment by iHiD** [comment]
@glennj Thanks.

@kntsoriano Can you run up Exercism locally and create a solution with this code in on the Lisp track and see if it hangs please? Presuming it does, try bumping Prism locally and see if that fixes it? If that doesn't, and you see a different quick fix, execute it. If that doesn't work and you don't have an obvious fix, tell me here and I'll prioritise it. Thanks :)

**Comment by kntsoriano** [comment]
@iHiD Upgrading prism fixes this. I've opened https://github.com/exercism/website/pull/694.
