### ISSUE TITLE
Mentoring queue on java track gets longer

### ISSUE THREAD

**Issue by DonMaks** [exercism/bugs#18]
Hello

I'm enrolled in the java track and are waiting for my matrix exercise to get reviewed.
https://exercism.io/my/solutions/1ea8e3a6232042a0bdca97f83f9a944d

The estimated waiting time is 12 days, but I've waited for almost 4 weeks now. Further the queue in  front of me seems to get bigger, i.e. yesterday there were 62 solutions in front of me on the java track, now its 80. Is that the expected behavior of the mentoring queue?

Thanks, love the site :)

**Comment by kntsoriano** [comment]
@iHiD Might need your help confirming this. This is what I think causes the bug: https://github.com/exercism/website/blob/79f2844273e3b0bbece44b36946babe6a1148dd8/app/services/solutions_to_be_mentored.rb#L103.

Old users might be checking back to the website to see whether they've moved in the queue.

**Comment by iHiD** [comment]
Yeah. That's possible. I'll assign some time next week for me to look through the database and check things. Thanks.
