### ISSUE TITLE
Non-Signed-In users can join `javascript-legacy` via the big hexagon field

### ISSUE THREAD

**Issue by NobbZ** [exercism/bugs#20]
@NobbZ commented on [Tue Aug 20 2019](https://github.com/exercism/cli/issues/874)

If a user is not logged in and visit exercism.io, they see the collection of hexagons, representing a track each. The `JS` labeled hexagon links to the `javascript-legacy` track which shouldn't be accessible for anyone who has not submitted an exercise to this track before it was deprecated and joined with the former `ecmascript` track.

Users can then click "Join" and register/login and are then member of that track.

This was discovered because a fresh exercism user came into the gitter and reported download problems with their exercise, the error message they reported was:

```plain
Error: failed to parse API error response: invalid character 'o' in literal null (expecting 'u')
```

This happened on downloading. This error message might be related (but not has to be) to the fact that the track shouldn't be accessible anymore. We did not follow this, as joining and downloading from regular `javascript` track worked.

Suggestions:

1. Replace the link of the hexagon with the correct track to the **current** `javascript` track.
2. Remove the JOIN button from the legacy tracks landing page

---

@NobbZ commented on [Tue Aug 20 2019](https://github.com/exercism/cli/issues/874#issuecomment-523003271)

Addition: I just realised, that there is also an "ecmascript" hexagon (logo labeled ES), that links to the `javascript` track.

Perhaps we should just remove the hexagon pointing to `javascript-legacy` and put its icon on the link to the current `javascript` track that has the "ES" icon?

Maybe this also requires a reordering of the hexagons.

**Comment by ReneCode** [comment]
I got the same error while starting the first javascript lesson "Hello World"

    exercism download --exercise=hello-world-a2b2f0b0-093d-48cb-a632-4ba201026ab9 --track=javascript-legacy

    Error: failed to parse API error response: invalid character 'o' in literal null (expecting 'u')

(I'm logged in - on the exercism.io page)
What should I do ?

**Comment by NobbZ** [comment]
Please do not follow the `javascript-legacy` tracks, its not meant to be solved anymore. Do the `javascript` track instead.

**Comment by ReneCode** [comment]
> Please do not follow the `javascript-legacy` tracks, its not meant to be solved anymore. Do the `javascript` track instead.

@NobbZ ok, no errors - that's fine. Thank you.  But also no content. my "~/Exercism/users" folder is empty :-(

**Comment by iHiD** [comment]
@NobbZ Thanks for identifying this.

I have:

- Updated the JavaScript track to have the correct icon (JS not ES).
- Removed the incorrect version from the hex.

> Remove the JOIN button from the legacy tracks landing page

After thought, I'm not going to do this as many maintainers use this button to join tracks that are WIP. However, as the track is now no longer linked to around the site, I think the issues should stop.

As a side note, I suspect the track only recently reappeared when I did a big db update. I'm unsure as to why that happened and will investigate further.
