### ISSUE TITLE
Isogram artifact remains in the Elm track

### ISSUE THREAD

**Issue by syeo66** [exercism/bugs#21]
I was able to download it by removing the whole uuid part from 
`exercism download --exercise=isogram-ed04a8a4-05aa-4289-bdf0-33a4cd6ca36d --track=elm`

but then my uploaded solution was not recognized after submitting (as was to be expected, I guess).

**Comment by iHiD** [comment]
Is this fixed now?

**Comment by syeo66** [comment]
Yes, it is. Thanks
