### ISSUE TITLE
D programming language syntax highlighting trouble with quotes

### ISSUE THREAD

**Issue by bkhl** [exercism/bugs#22]
It looks like the syntax highlighting for D can't handle single quotes inside strings:

![screenshot](https://user-images.githubusercontent.com/34634/63636116-529da280-c695-11e9-99a1-d487b74272db.png)

**Comment by bkhl** [comment]
Yes, it happens there also:

![prism-screenshot](https://user-images.githubusercontent.com/34634/63637879-0f9af980-c6ac-11e9-99ae-567e8da30e0c.png)

**Comment by iHiD** [comment]
OK, thanks for checking. So I think you'll need to open an issue at https://github.com/PrismJS/prism - Not much we can do until they fix it.

**Comment by bkhl** [comment]
There we go, maybe you can add in what version you are currently using there.

**Comment by iHiD** [comment]
Thanks. @kntsoriano is currently upgrading it actually, so I'll let him do that once that PR is merged.

**Comment by bkhl** [comment]
I see there's a pull request for a fix already:  https://github.com/PrismJS/prism/pull/2029

**Comment by iHiD** [comment]
Nice!

**Comment by bkhl** [comment]
I saw that pull request has been merged now.

**Comment by iHiD** [comment]
@kntsoriano Presuming that PR has also been released, could you upgrade Prism again pls :)

**Comment by kntsoriano** [comment]
@iHiD Prism hasn't released a new version yet. We'd have to wait as we rely on a CDN.

**Comment by iHiD** [comment]
OK, cool. Let's keep an eye on it. @bkhl If you notice it gets released, ping us here and we'll upgrade it :)
