### ISSUE TITLE
Code in list element has wrong styling

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/bugs#29]
As per @iHiD , @kntsoriano can you look at this please?

The following css selector makes code tags look great at the "top-level".
```css
body.prism-dark .editable-text .editable-text-html pre[class*="language-"], 
body.prism-dark .new-editable-text .preview-area pre[class*="language-"] {

}
```

However, nesting a code tag in a list, will make the following, incorrect, css selector active:

```css
.editable-text .editable-text-html p code, 
.editable-text .editable-text-html li code, 
.new-editable-text .preview-area p code, 
.new-editable-text .preview-area li code {
  ...
}
```

The latter adds:

```css
{ 
  border: 1px solid #fafafa;
  background: #f5f5f5;
}
```

This produces:

![image](https://user-images.githubusercontent.com/1964376/65474052-a826c400-de7a-11e9-9027-ef531a51e718.png)

**Comment by kntsoriano** [comment]
Thanks for the thorough report :)
