### ISSUE TITLE
Markdown does not support strikethrough

### ISSUE THREAD

**Issue by pedantic79** [exercism/bugs#30]
I don't know if this is a regression, but I noticed that the markdown on the website doesn't support ~~strikethrough~~.  

Looks like `~~strikethrough~~` syntax is part of the [GitHub Flavored Markdown extension](https://github.github.com/gfm/#strikethrough-extension-) and not part of [Common Mark](https://commonmark.org/help/). It would be nice to strikeout text that was previously mentioned without resorting to html.

Thanks

**Comment by iHiD** [comment]
@kntsoriano Pretty sure this is a regression. Could you see if you can track it down pls?
