### ISSUE TITLE
Notifcations for deleted exercises aren't removed from mentor's notification list

### ISSUE THREAD

**Issue by paparomeo** [exercism/bugs#33]
One of my students deleted their exercise (see exercism/exercism#4595), but the notifications I had in mentors notifications list about that exercise weren't removed (I've left them there to help solving this issue). My username on exercism is also `paparomeo`.

**Comment by iHiD** [comment]
> @iHiD I don't have access to the bugs repo

You do now :)

I think the easiest first step is deleting stale notifications (as @kntsoriano has PR'd). A nice extra would be to add an extra notification, which says "X deleted their solution", but I'm not sure where that would go when the person clicks it, and if it wasn't clickable, how it would disappear, so this would need some extra thinking, and is probably a lower priority.
