### ISSUE TITLE
https://exercism.io/tracks/fortran/tests page not rendering correctly

### ISSUE THREAD

**Issue by pclausen** [exercism/bugs#38]
https://exercism.io/tracks/fortran/tests page not rendering correctly, see after "ctest V"

![Screenshot at 2019-10-21 21-33-06](https://user-images.githubusercontent.com/616409/67240577-0632d100-f452-11e9-877f-3ba201e28881.png)

**Comment by iHiD** [comment]
This is a regression caused by https://github.com/exercism/website/pull/612 - I'll add a fix now.

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/787

Looks much better now. Thanks!
