### ISSUE TITLE
Ruby 'High Scores' solution page is completely blank

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/bugs#8]
I had previously started the Ruby 'High Scores' exercise but not completed it. When I checked the solution page most recently, everything was blank:

![screenshot from 2018-12-13 08-48-07](https://user-images.githubusercontent.com/1254212/49964261-0edc8180-fee8-11e8-9eeb-6dd889cd0772.png)

This was already opened in the exercism Ruby repo at exercism/ruby#898

**Comment by NobbZ** [comment]
When you use `exercism download` do you get the correct files downloaded?

**Comment by PatrickMcSweeny** [comment]
> When you use exercism download do you get the correct files downloaded?

Yes

**Comment by NobbZ** [comment]
@ihid isn't this a bug in the website then?

@PatrickMcSweeny could you tell us the UUID of the exercise? Or the URL is fine as well, we can read it from there.

**Comment by PatrickMcSweeny** [comment]
@NobbZ the uuid is 2e556b033b274a168810746bff8f9b24

**Comment by iHiD** [comment]
I really don't understand this. I've just (temporarily) changed the `user_id` of the solution to be me and I log in and I can see it fine. And I can run `Solution.find(...).instructions` and get everything normally in a `rails c`. So weird.

**Comment by PatrickMcSweeny** [comment]
Weird, I am now able to view the instructions. I see that the other issue related to this problem is still open so I will close this one.

**Comment by PatrickMcSweeny** [comment]
Computers, amirite?
