### ISSUE TITLE
Teams: text stays in input box after pressing Comment

### ISSUE THREAD

**Issue by matthewmcgarvey** [exercism/bugs#9]
Below is a picture right after I pressed comment

<img width="584" alt="Screen Shot 2019-03-27 at 1 00 10 PM" src="https://user-images.githubusercontent.com/17329408/55100794-b3965f80-5090-11e9-9338-9aeda5eaab8f.png">

**Comment by kntsoriano** [comment]
@matthewmcgarvey Could you check if you're happy with how the comment box on the team page works now? Thanks.
